In [18]:
# 데이터 정렬
import pandas as pd
path = 'C:/juehyeon/aice_test/materials/datasets/'
df = pd.read_csv(path + 'heart.csv')

In [6]:
## 특정 열 기준으로 정렬 sort_values(by = 기준 열, ascending = True)
df_sorted_by_age = df.sort_values(by = 'age', ascending = True)
print(df_sorted_by_age)

     age  sex  cp  trtbps  chol  fbs  restecg  thalachh  exng  oldpeak  slp  \
72    29    1   1     130   204    0        0       202     0      0.0    2
58    34    1   3     118   182    0        0       174     0      0.0    2
125   34    0   1     118   210    0        1       192     0      0.7    2
239   35    1   0     126   282    0        0       156     1      0.0    2
65    35    0   0     138   183    0        1       182     0      1.4    2
..   ...  ...  ..     ...   ...  ...      ...       ...   ...      ...  ...
60    71    0   2     110   265    1        0       130     0      0.0    2
151   71    0   0     112   149    0        1       125     0      1.6    1
129   74    0   1     120   269    0        0       121     1      0.2    2
144   76    0   2     140   197    0        2       116     0      1.1    1
238   77    1   0     125   304    0        0       162     1      0.0    2

     caa  thall  output
72     0      2       1
58     0      2       1
125    0      2       1
239    0      3       0
65     0      2       1
..   ...    ...     ...
60     1      2       1
151    0      2       1
129    1      2       1
144    0      2       1
238    3      2       0

[303 rows x 14 columns]

In [8]:
## 여러 열 기준 정렬 sort_values(by = ['기준열1', '기준열2], ascending = ['오름차순', '내림차순'])
df_sorted_by_multiple = df.sort_values(by = ['age', 'thalachh'], ascending = [True, False])
df_sorted_by_multiple.head()

,age,sex,cp,trtbps,chol,fbs,restecg,thalachh,exng,oldpeak,slp,caa,thall,output
72,29,1,1,130,204,0,0,202,0,0.0,2,0,2,1
125,34,0,1,118,210,0,1,192,0,0.7,2,0,2,1
58,34,1,3,118,182,0,0,174,0,0.0,2,0,2,1
65,35,0,0,138,183,0,1,182,0,1.4,2,0,2,1
157,35,1,1,122,192,0,1,174,0,0.0,2,0,2,1

In [10]:
## 인덱스 기준 정렬 : sort_index()
df_sorted_by_index = df.sort_index(ascending = False)
df_sorted_by_index.head()

,age,sex,cp,trtbps,chol,fbs,restecg,thalachh,exng,oldpeak,slp,caa,thall,output
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0

In [15]:
### 인덱스를 특정 열로 설정
data = {'Name' : ['Alice', 'Bob', 'Charlie'],
        'Age' : [25, 30, 35]}
df_n = pd.DataFrame(data)
df_n.set_index('Name', inplace = True)
print(df_n)

         Age
Name
Alice     25
Bob       30
Charlie   35

In [16]:
### 인덱스를 기본값으로 재설정
df_n.reset_index(inplace = True)
print(df_n)

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

In [20]:
## 열 이름 기준으로 정렬 : sort_index(axis = 1)
df_sorted_by_columns = df.sort_index(axis = 1, ascending = True)
print(df_sorted_by_columns.head())

   age  caa  chol  cp  exng  fbs  oldpeak  output  restecg  sex  slp  \
0   63    0   233   3     0    1      2.3       1        0    1    0
1   37    0   250   2     0    0      3.5       1        1    1    0
2   41    0   204   1     0    0      1.4       1        0    0    2
3   56    0   236   1     0    0      0.8       1        1    1    2
4   57    0   354   0     1    0      0.6       1        1    0    2

   thalachh  thall  trtbps
0       150      1     145
1       187      2     130
2       172      2     130
3       178      2     120
4       163      2     120