In [1]:
import pandas as pd
path = 'C:/juehyeon/aice_test/materials/datasets/'
df = pd.read_csv(path + 'heart.csv')

In [2]:
df.columns = ['나이', '성별', '흉통유형', '안정시혈압', '콜레스테롤', '공복혈당', '심전도', '최대 심박수',
              '운동유발협심증', 'ST 우울증', '운동후 ST경사', '주요혈관수', '결함유형', '심장질환여부']

In [3]:
# 그룹화와 집계 
## 성별을 기준으로 데이터 그룹화
groupped= df.groupby('성별')
groupped.size()

성별
0     96
1    207
dtype: int64

In [5]:
## 성별별 주요 열의 평균 집계
groupped_mean = groupped.mean()
print(groupped_mean)

           나이      흉통유형       안정시혈압       콜레스테롤     공복혈당       심전도  \
성별
0   55.677083  1.041667  133.083333  261.302083  0.12500  0.572917
1   53.758454  0.932367  130.946860  239.289855  0.15942  0.507246

        최대 심박수   운동유발협심증    ST 우울증  운동후 ST경사     주요혈관수      결함유형    심장질환여부
성별
0   151.125000  0.229167  0.876042  1.427083  0.552083  2.125000  0.750000
1   148.961353  0.371981  1.115459  1.386473  0.811594  2.400966  0.449275

In [6]:
## 여러 집계 함수 사용 : agg()
### agg() : 여러 열에 다양한 집계 함수 동시 적용, 딕셔너리 형태로 열 이름과 함수 목록 지정
groupped_stats = groupped.agg({
    '나이' : ['max' , 'min'],
    '콜레스테롤' : ['mean', 'std']
})
print(groupped_stats)

    나이           콜레스테롤
   max min        mean        std
성별
0   76  34  261.302083  65.088946
1   77  29  239.289855  42.782392

In [8]:
## 다중 그룹화
groupped_multi = df.groupby(['성별', '흉통유형']).mean()
groupped_multi

                나이       안정시혈압       콜레스테롤      공복혈당       심전도      최대 심박수  \
성별 흉통유형
0  0     57.256410  138.589744  267.538462  0.128205  0.538462  145.282051
   1     51.944444  128.055556  251.444444  0.111111  0.555556  162.833333
   2     54.971429  127.885714  261.057143  0.114286  0.600000  151.800000
   3     63.250000  147.500000  247.000000  0.250000  0.750000  149.500000
1  0     55.105769  129.557692  243.605769  0.125000  0.451923  138.759615
   1     51.031250  128.593750  241.031250  0.093750  0.656250  162.187500
   2     52.538462  132.057692  231.134615  0.250000  0.596154  158.173077
   3     54.315789  139.473684  235.052632  0.210526  0.315789  157.315789

          운동유발협심증    ST 우울증  운동후 ST경사     주요혈관수      결함유형    심장질환여부
성별 흉통유형
0  0     0.461538  1.356410  1.179487  0.820513  2.282051  0.461538
   1     0.111111  0.461111  1.666667  0.555556  2.000000  0.888889
   2     0.057143  0.474286  1.571429  0.257143  2.028571  0.971429
   3     0.000000  1.575000  1.500000  0.500000  2.000000  1.000000
1  0     0.596154  1.393269  1.288462  1.019231  2.509615  0.201923
   1     0.062500  0.234375  1.687500  0.343750  2.218750  0.781250
   2     0.173077  1.015385  1.461538  0.807692  2.326923  0.673077
   3     0.210526  1.352632  1.210526  0.473684  2.315789  0.631579

In [11]:
# Pivot Table 조작 : 특정 기준에 따라 데이터를 요약하거나 변환하는데 사용하는 도구
## 1. pivot table 생성
pivot = df.pivot_table(index = '성별', columns = '흉통유형', values = '최대 심박수', aggfunc = 'mean')
### 해석 ) 성별을 인덱스로 지정, 흉통유형을 열로 지정, 최대 심박수 값을 피벗 테이블에서 요약 데이터로 사용, 최대 심박수의 평균값 계산
pivot

흉통유형           0           1           2           3
성별
0     145.282051  162.833333  151.800000  149.500000
1     138.759615  162.187500  158.173077  157.315789