# K - Nearest Neighbors(K-NN, K-최근접 이웃)
: 가장 간단하지만 효과적인 머신러닝 분류 / 회귀 알고리즘 중 하나. 새로운 데이터를 예측할 때 **가까운 데이터 K개를 찾아서 다수결 혹은 평균으로 결정**
1) 핵심 개념
   1) 분류 (Classification) : K개의 이웃 중 가장 많은 클래스를 가진 값으로 예측
   2) 회귀 (Logistics) : K개의 이웃의 평균값으로 예측
   3) 거리 계산 : 주로 유클리드 거리 사용
   4) K값 : K가 너무 적으면 민감해지고, 너무 크면 평균화되어 일반화가 떨어짐
2) 예측 방식 : 새로운 데이터가 들어왔을 때 이미 알고 있는 데이터 중 가장 가까운 K개를 찾아,
   - 분류 문제에서는 다수결로
   - 회귀 문제에서는 평균을 내어 값 예측
3) 작동 원리 (ex: 환자의 심장병 예측)
   1) 새로운 데이터가 들어옴 (환자 정보 입력) 
   2) 모든 기존 데이터와의 거리 계산 (기존에 있던 모든 환자들과 입력된 새 환자의 건강 수치가 얼마나 유사한지 계산)
   3) 가장 가까운 K개의 데이터 선택 (모든 환자와의 거리 계산 후 가장 가까운 K명 선택)
   4) 이웃의 정보를 바탕으로 예측값 결정
      - 분류 : 가장 가까운 이웃 중 심장병이 있는 사람이 더 많으면 심장병이 있을 확률이 높다고 판단 (다수결 방식)
      - 회귀 : 이웃들의 점수나 수치 값을 평균 내어 새로운 환자 결과 예측

In [1]:
# 모델 생성 코드
## 필요 라이브러리 불러오기
import pandas as pd 
from sklearn.model_selection import train_test_split 
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix 
import warnings
warnings.filterwarnings('ignore')

In [4]:
## 1. 데이터 불러오기
path = "C:/juehyeon/aice_test/materials/datasets/"
data = pd.read_csv(path + 'heart.csv')
data.head()

,age,sex,cp,trtbps,chol,fbs,restecg,thalachh,exng,oldpeak,slp,caa,thall,output
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [7]:
## 2. X,y분리
X = data.drop('output', axis=1)
y = data['output']

In [8]:
## 3. 데이터 분할
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size = 0.2, random_state = 42
)

In [9]:
## 4. K-NN 데이터 모델 생성
model = KNeighborsClassifier(n_neighbors = 5) ## KNN 분류 모델 객체 생성 
model.fit(X_train, y_train)

KNeighborsClassifier()

In [13]:
## 5. 예측 및 평가
y_pred = model.predict(X_test)
print("정확도(Accuracy) : ", accuracy_score(y_test, y_pred))
print("혼동행렬 : \n", confusion_matrix(y_test, y_pred))

정확도(Accuracy) :  0.6885245901639344
혼동행렬 :
 [[18 11]
 [ 8 24]]

In [14]:
# 와인 데이터로 실습하기 (회귀) 
from sklearn.neighbors import KNeighborsRegressor ## KNN 회귀모델 생성 + 학습할 수 있는 클래스 
from sklearn.metrics import mean_squared_error, r2_score

In [15]:
## 1. 데이터 불러오기
wine = pd.read_csv('C:/juehyeon/aice_test/materials/datasets/winequality-white.csv')
wine.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,quality,alcohol
0,7.0,0.27,0.36,20.7,45.00,45.0,170.0,1.001,3.00,0.45,6,"R$ 45.512,00"
1,6.3,0.30,0.34,1.6,49.00,14.0,132.0,994.000,3.30,0.49,6,"R$ 45.421,00"
2,8.1,0.28,0.40,6.9,0.05,30.0,97.0,9.951,3.26,0.44,6,"R$ 45.301,00"
3,7.2,0.23,0.32,8.5,58.00,47.0,186.0,9.956,3.19,0.40,6,"R$ 45.544,00"
4,7.2,0.23,0.32,8.5,58.00,47.0,186.0,9.956,3.19,0.40,6,"R$ 45.544,00"

In [16]:
## 2. X, y 데이터 분리
X = wine.drop(['quality', 'alcohol'], axis = 1)
y = wine['quality']

In [17]:
## 3. 데이터 분할
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [19]:
## 4. K-NN 회귀 모델 생성(K=5)
reg = KNeighborsRegressor(n_neighbors = 5)
reg.fit(X_train, y_train)

KNeighborsRegressor()

In [20]:
## 5. 예측 및 평가
y_pred = reg.predict(X_test)
print("MSE :", mean_squared_error(y_test,y_pred))
print("R2 Score: ", r2_score(y_test, y_pred))

MSE : 0.6688163265306122
R2 Score:  0.13642411172835867

In [24]:
# k값 변경 
## 모델 생성 코드
for k in [1, 3, 5, 7, 9] : # K값을 1,3,5,7,9로 바꿔가며 실험 
    model = KNeighborsClassifier(n_neighbors = k) # 반복중인 K값 적용하여 KNN 모델 생성
    model.fit(X_train, y_train) # 학습 데이터를 모델에 적용하여 학습 
    acc = accuracy_score(y_test, model.predict(X_test)) # 실제 정답과 예측 결과를 비교하여 정확도를 계산 
    print(f"K = {k} , 정확도 : {acc}")

K = 1 , 정확도 : 0.5622448979591836
K = 3 , 정확도 : 0.4785714285714286
K = 5 , 정확도 : 0.4857142857142857
K = 7 , 정확도 : 0.49183673469387756
K = 9 , 정확도 : 0.48673469387755103

[ 참고 ] : 
- k = 1일 경우 가장 가까운 1개의 데이터만 참고하므로, 노이즈에 민감하고 과적합 위험이 있음
- k = 5 또는 k = 7 : 보통 가장 안정적 성능
- k가 너무 크면 : 주변 데이터가 너무 많아져서 클래스 간 경계가 흐려지고 일반화가 잘 되지 않을 가능성이 있음