# Support Vector Machine (SVM, 서포트 벡터 머신)
: 데이터를 분류하거나 예측할 때 가장 넓은 마진을 가진 경계선을 찾아주는 모델. 데이터를 단순히 나누기 보다는 확실히 구분하는 선을 찾는 것이 핵심

1) 핵심 개념
   - Hyperplane(초평면) : 데이터를 나누는 기준선 또는 기준면
   - Margin(마진, 여백) : 두 클래스 사이의 거리 -> 마진이 최대화되도록 학습
   - 서포트 벡터 : 마진 경계에 가까이 있는 데이터 포인트 (결정에 직접 영향을 줌)
   - Kernel Trick (커널 트릭) : 선형으로 나눌 수 없는 데이터를 고차원으로 변환하여 선형 분리가 가능하게 만듦
2) 작동 원리 : 데이터 분류할 때 **"선 하나를 단순히 그어 나누는 것"** 이 아닌 **"가장 경계가 명확하고 안전하게 나눌 수 있는 선"** 을 찾는 알고리즘
   1) 데이터 분포를 살펴보기
   2) 데이터를 나눌 수 있는 여러 개의 선 중 가장 안정적인 경계선을 고름
   3) 마진이 가장 넓은 선을 선택 : 마진이 넓을 수록 새 데이터가 들어와도 헷갈릴 가능성이 낮아지고 예측이 더 안정적임
   4) 새 데이터가 들어오면 SVM은 해당 데이터가 결정 경계의 어느 쪽에 위치하는지를 판단하여 경계의 한 쪽이면 0, 다른쪽이면 클래스 1로 분류
   5) 종종 선형으로 깔끔하게 나뉘지 않는 경우가 많아 Kernel Trick이라는 기술을 사용해 데이터를 더 높은 차원으로 변환한 뒤 직선으로 나눌 수 있게 만듦

In [3]:
## 심장병 예측 실습
### 1. 필요 라이브러리 불러오기
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix
import warnings
warnings.filterwarnings('ignore')

In [5]:
### 2. 데이터불러오기
df = pd.read_csv('C:/juehyeon/aice_test/materials/datasets/heart.csv')
df.head()

,age,sex,cp,trtbps,chol,fbs,restecg,thalachh,exng,oldpeak,slp,caa,thall,output
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [7]:
### 3. 입력 (X), 출력 (y) 나누기 
X = df.drop('output', axis = 1)
y = df['output']

In [8]:
### 4. 데이터 분할
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [9]:
### 5. SVM 모델 생성 및 학습 (기본 선형)
model = SVC(kernel = 'linear')
model.fit(X_train, y_train)

SVC(kernel='linear')

In [12]:
### 6. 예측 및 평가
y_pred = model.predict(X_test)
print("Accuracy(정확도): ", accuracy_score(y_test, y_pred))
print("Confusion Matrix(혼동 행렬) :\n", confusion_matrix(y_test, y_pred))

Accuracy(정확도):  0.8688524590163934
Confusion Matrix(혼동 행렬) :
 [[25  4]
 [ 4 28]]

In [13]:
## 와인 데이터 실습(회귀)
### 1. 필요 라이브러리 불러오기
from sklearn.svm import SVR # 회귀 모델 생성용
from sklearn.metrics import mean_squared_error, r2_score

In [14]:
### 2. 데이터 불러오기
wine = pd.read_csv('C:/juehyeon/aice_test/materials/datasets/winequality-white.csv')
wine.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,quality,alcohol
0,7.0,0.27,0.36,20.7,45.00,45.0,170.0,1.001,3.00,0.45,6,"R$ 45.512,00"
1,6.3,0.30,0.34,1.6,49.00,14.0,132.0,994.000,3.30,0.49,6,"R$ 45.421,00"
2,8.1,0.28,0.40,6.9,0.05,30.0,97.0,9.951,3.26,0.44,6,"R$ 45.301,00"
3,7.2,0.23,0.32,8.5,58.00,47.0,186.0,9.956,3.19,0.40,6,"R$ 45.544,00"
4,7.2,0.23,0.32,8.5,58.00,47.0,186.0,9.956,3.19,0.40,6,"R$ 45.544,00"

In [15]:
### 3. X, y 데이터 분리
X = wine.drop(['quality', 'alcohol'], axis = 1)
y = wine['quality']

In [16]:
### 4. 데이터 분할
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [19]:
### 5. SVM 모델 생성 및 학습
reg = SVR(kernel = 'rbf') # 비선형 커널 사용
reg.fit(X_train, y_train)

SVR()

In [22]:
### 6. 예측 및 평가
y_pred = reg.predict(X_test)
print("MSE: ", mean_squared_error(y_test, y_pred))
print("R :", r2_score(y_test, y_pred))

MSE:  0.6866432309760008
R : 0.11340600611269758